# Site specific info
title: "iUFBA"
name: "iUFBA"
keywords: "InfoUFBA, UFBA, Informações UFBA, Calouro UFBA, Comunidade UFBA, iUFBA"
author: "gjuniioor"
baseurl: ""
url: "//iufba.github.io"
github_url: "https://github.com/iUFBA"
description: "Informações para comunidade UFBA"
cover: ""
fanpage_id: ""

# Site general settings
lang: "pt_BR"
lang_alternate: ""
ssl: true # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: 
facebook: 
github: 
google: 

# Build settings
markdown: kramdown
permalink: /:categories/:title/
